#!/bin/bash

if [ ! -d "$LWE_HOME" ] ; then
  echo 'Aborting: $LWE_HOME is not set'
  exit 1
fi

############################## START LWE ##############################
PATH="$LWE_HOME/tools/jruby/bin:$PATH:/usr/local/bin"

jruby -S gem list

source "$HOME/.rvm/scripts/rvm"
cd "$WORKSPACE"

java -version
jruby -v

rvm list

rvm gemset name
rvm gemset list

rvm gemset create lws_blacklight
rvm gemset use lws_blacklight

rm -rf .bundle
jruby -S bundle install --local

# Just to test out the CI infrastructure
jruby -S rake routes

jruby -S warble executable war



